### PR TITLE
Fix for junk data in package read.

### LINKED ISSUE #31: pkg: something looks wrong when reading files from .pkg
I've got a lot of weird characters when reading package. (checkout & test PR #28) to view it.

### PR DESCRIPTION
**Pull request by Johannestegner**
This PR fixes #31 by - instead of creating a buffer with the size of the expected result - creating a empty byte buffer which is then populated with `ReadFrom`.

Tests have been updated to be able to catch this in a better way as well.

### CODE REVIEW

File: internal/pkg/package.go [hunk 1]
```diff
@@ -84,8 +84,8 @@ func Read(path string) (map[string][]byte, error) {
 			return nil, err
 		}
 
-		out := bytes.NewBuffer(make([]byte, header.Size))
-		if _, err := io.Copy(out, tr); err != nil {
+		out := bytes.NewBuffer([]byte{})
+		if _, err := out.ReadFrom(tr); err != nil {
```
Comment (creekorful) [inline internal/pkg/package.go:88]: if you use ReadFrom, then you can pre-allocate the buffer.
See: https://golang.org/pkg/bytes/#Buffer.ReadFrom

Comment (Johannestegner) [reply internal/pkg/package.go:88]: Seems like it appends:

> ReadFrom reads data from r until EOF and appends it to the buffer

I will dig in to it a bit deeper later to see if we can change it to something nicer, hehe.

Comment (creekorful) [reply internal/pkg/package.go:88]: You're totally right, my bad!

**Review by creekorful — APPROVED** [review]
